// <auto-generated />
namespace VnVGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adds_owner_to_gallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adds_owner_to_gallery));
        
        string IMigrationMetadata.Id
        {
            get { return "201611011429501_adds_owner_to_gallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
